### ISSUE TITLE
RCTF Online Platform not working

### ISSUE THREAD

**Issue by rukyr97** [aliasrobotics/rctf-list#1]
When i try to start my first scenario, it gets stuck in stage 1/4 for ages. Not moving and not explaining any kind of error. It just stay in the first stage for hours.
I don't know how i can be more specific. Sorry in advance!

**Comment by olaldiko** [comment]
Hi, @Rukyr97, please, try again now, it should be solved now.

**Comment by rukyr97** [comment]
It is working. Thanks alot!
